#!/bin/bash

# Script de pre-push: llama al compilador y ejecuta los tests antes de hacer push,
# si alguno de los dos comandos da error cancela el push.

echo "Compilando..."
if [[ `./vendor/bin/phpstan analyse -c phpstan.neon -l 5 src --memory-limit 1024M -q || echo Err` ]]; then
	echo "Error en complilación, cancelando push."
	echo
	exit 1
fi
echo "Compilado OK"
echo

echo "Corriendo tests..."
if [[ `./vendor/bin/phpunit --stop-on-failure > /dev/null || echo Err` ]]; then
	echo "Error en tests, cancelando push."
	echo
	exit 1
fi
echo "Tests OK"
echo

exit 0

